### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by NguyenVanThanhHust** [nguyenphan99/LoGoViT#1]
Can you release pretrained models and running instruction

**Comment by nguyenphan99** [comment]
FYI: 
1. The Pre-trained model can both be downloaded automatically or manually by inline code at line 86-117 https://github.com/nguyenphan99/LoGoViT/blob/main/model/backbones/vit_pytorch.py
2. You could run the code via file run.sh. You could also take some of the config modifications, which could be found at https://github.com/damo-cv/TransReID/tree/main
